### ISSUE TITLE
pip install doesn't work

### ISSUE THREAD

**Issue by Shashi456** [skillachie/news-corpus-builder#5]
The news corpus builder pip install does not get completed . I think the issue for this is using beautifulsoup , it has been termed OBSOLETE and they have migrated to beautifulsoup4 if this problem could be solved asap it would be good , or if there were a turn around this problem that would be appreciated as well

```
Collecting` beautifulsoup (from goose-extractor)
  Using cached BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\VENKAT~1\AppData\Local\Temp\pip-build-i083otnm\beautifulsoup\setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\VENKAT~1\AppData\Local\Temp\pip-build-i083otnm\beautifulsoup\
```

Although i understand that this is because of my python running 3+ , will the software be migrated anytime soon .

**Comment by Shashi456** [comment]
I'm sorry about this , i put this post in a hurry , the issue does not lie within news_corpus_builder but within goose extractor which needs the beautifulsoul module too .
